service: dev-anon-dynamodb-crud-api
// API KEY FOR CONVERSION: 613501719a-93e03da33c-rz4b6y


provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

  environment:
    DYNAMO_TABLE_NAME: ${self:custom.postsTableName}

custom:
  tableName: goods-cost
  postsTableName: anon-posts-table-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function

functions:
  getPost:
    handler: api.getPost
    name: anon-get-post
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: anon-post/{productId}
          method: GET
          request: 
            parameters: 
              querystrings:
                currency: false
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:GetItem"
        Resource: !GetAtt PostsTable.Arn

  createPost:
    handler: api.createPost
    name: anon-create-post
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: anon-post
          method: POST
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
        Resource: !GetAtt PostsTable.Arn

  updatePost:
    handler: api.updatePost
    name: anon-update-post
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: anon-post/{productId}
          method: PUT
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:UpdateItem"
        Resource: !GetAtt PostsTable.Arn

  deletePost:
    handler: api.deletePost
    name: anon-delete-post
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: anon-post/{productId}
          method: DELETE
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:DeleteItem"
        Resource: !GetAtt PostsTable.Arn

  getAllPosts:
    handler: api.getAllPosts
    name: anon-get-all-posts
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: anon-posts
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:Scan"
        Resource: !GetAtt PostsTable.Arn

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.postsTableName}
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DynamoTableItems:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName:${self:custom.tableName} // Referencing this file, the tableName.
        AttributeDefinitions:
          - AttributeName: ID // Because it's an array we use the (-).
            AttributeType: S // For string.
        KeySchema:
          - AttributeName: ID
            KeyType: HASH // Tells dyynamo exactly what type of format these attributes are in.
      BillingMode: PAY_PER_REQUEST // Makes it so that we only have to pay for what we use.